version: '3.8'
services:
  mysql: 
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'test-golang'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
# Names our volume
volumes:
  mysql:
    driver: local